# Generated by Django 5.1.5 on 2025-02-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='xray_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
